export * from './addonApi';
import { AddonApi } from './addonApi';
export * from './branchingModelApi';
import { BranchingModelApi } from './branchingModelApi';
export * from './branchrestrictionsApi';
import { BranchrestrictionsApi } from './branchrestrictionsApi';
export * from './commitsApi';
import { CommitsApi } from './commitsApi';
export * from './commitstatusesApi';
import { CommitstatusesApi } from './commitstatusesApi';
export * from './defaultApi';
import { DefaultApi } from './defaultApi';
export * from './deployApi';
import { DeployApi } from './deployApi';
export * from './deploymentsApi';
import { DeploymentsApi } from './deploymentsApi';
export * from './downloadsApi';
import { DownloadsApi } from './downloadsApi';
export * from './issueTrackerApi';
import { IssueTrackerApi } from './issueTrackerApi';
export * from './pipelinesApi';
import { PipelinesApi } from './pipelinesApi';
export * from './projectsApi';
import { ProjectsApi } from './projectsApi';
export * from './propertiesApi';
import { PropertiesApi } from './propertiesApi';
export * from './pullrequestsApi';
import { PullrequestsApi } from './pullrequestsApi';
export * from './refsApi';
import { RefsApi } from './refsApi';
export * from './repositoriesApi';
import { RepositoriesApi } from './repositoriesApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './snippetApi';
import { SnippetApi } from './snippetApi';
export * from './snippetsApi';
import { SnippetsApi } from './snippetsApi';
export * from './sourceApi';
import { SourceApi } from './sourceApi';
export * from './sshApi';
import { SshApi } from './sshApi';
export * from './teamsApi';
import { TeamsApi } from './teamsApi';
export * from './usersApi';
import { UsersApi } from './usersApi';
export * from './webhooksApi';
import { WebhooksApi } from './webhooksApi';
export const APIS = [AddonApi, BranchingModelApi, BranchrestrictionsApi, CommitsApi, CommitstatusesApi, DefaultApi, DeployApi, DeploymentsApi, DownloadsApi, IssueTrackerApi, PipelinesApi, ProjectsApi, PropertiesApi, PullrequestsApi, RefsApi, RepositoriesApi, SearchApi, SnippetApi, SnippetsApi, SourceApi, SshApi, TeamsApi, UsersApi, WebhooksApi];
