/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ActorInputBean {
    /**
    * The account IDs of the users to add as default actors. You can add multiple account IDs separated by a comma. For example, `\"user\":[\"12345678-9abc-def1-2345-6789abcdef12\", \"abcdef12-3456-789a-bcde-f123456789ab\"]`.
    */
    'user'?: Array<string>;
    /**
    * The name of the group to add as a default actor. You can add multiple groups separated with a comma. For example, `\"group\":[\"project-admin\", \"jira-developers\"]`.
    */
    'group'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "Array<string>"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ActorInputBean.attributeTypeMap;
    }
}

