/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ActorsMap {
    /**
    * The user account ID of the user to add.
    */
    'user'?: Array<string>;
    /**
    * The name of the group to add.
    */
    'group'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "Array<string>"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ActorsMap.attributeTypeMap;
    }
}

