/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details of an application role.
*/
export class ApplicationRole {
    /**
    * The key of the application role.
    */
    'key'?: string;
    /**
    * The groups associated with the application role.
    */
    'groups'?: Array<string>;
    /**
    * The display name of the application role.
    */
    'name'?: string;
    /**
    * The groups that are granted default access for this application role.
    */
    'defaultGroups'?: Array<string>;
    /**
    * Determines whether this application role should be selected by default on user creation.
    */
    'selectedByDefault'?: boolean;
    /**
    * Deprecated.
    */
    'defined'?: boolean;
    /**
    * The maximum count of users on your license.
    */
    'numberOfSeats'?: number;
    /**
    * The count of users remaining on your license.
    */
    'remainingSeats'?: number;
    /**
    * The number of users counting against your license.
    */
    'userCount'?: number;
    /**
    * The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license.
    */
    'userCountDescription'?: string;
    'hasUnlimitedSeats'?: boolean;
    /**
    * Indicates if the application role belongs to Jira platform (`jira-core`).
    */
    'platform'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<string>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "defaultGroups",
            "baseName": "defaultGroups",
            "type": "Array<string>"
        },
        {
            "name": "selectedByDefault",
            "baseName": "selectedByDefault",
            "type": "boolean"
        },
        {
            "name": "defined",
            "baseName": "defined",
            "type": "boolean"
        },
        {
            "name": "numberOfSeats",
            "baseName": "numberOfSeats",
            "type": "number"
        },
        {
            "name": "remainingSeats",
            "baseName": "remainingSeats",
            "type": "number"
        },
        {
            "name": "userCount",
            "baseName": "userCount",
            "type": "number"
        },
        {
            "name": "userCountDescription",
            "baseName": "userCountDescription",
            "type": "string"
        },
        {
            "name": "hasUnlimitedSeats",
            "baseName": "hasUnlimitedSeats",
            "type": "boolean"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationRole.attributeTypeMap;
    }
}

