/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details of an application property.
*/
export class ApplicationProperty {
    /**
    * The ID of the application property. The ID and key are the same.
    */
    'id'?: string;
    /**
    * The key of the application property. The ID and key are the same.
    */
    'key'?: string;
    /**
    * The new value.
    */
    'value'?: string;
    /**
    * The name of the application property.
    */
    'name'?: string;
    /**
    * The description of the application property.
    */
    'desc'?: string;
    /**
    * The data type of the application property.
    */
    'type'?: string;
    /**
    * The default value of the application property.
    */
    'defaultValue'?: string;
    'example'?: string;
    /**
    * The allowed values, if applicable.
    */
    'allowedValues'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "desc",
            "baseName": "desc",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "defaultValue",
            "baseName": "defaultValue",
            "type": "string"
        },
        {
            "name": "example",
            "baseName": "example",
            "type": "string"
        },
        {
            "name": "allowedValues",
            "baseName": "allowedValues",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationProperty.attributeTypeMap;
    }
}

