/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details of an item associated with the changed record.
*/
export class AssociatedItemBean {
    /**
    * The ID of the associated record.
    */
    'id'?: string;
    /**
    * The name of the associated record.
    */
    'name'?: string;
    /**
    * The type of the associated record.
    */
    'typeName'?: string;
    /**
    * The ID of the associated parent record.
    */
    'parentId'?: string;
    /**
    * The name of the associated parent record.
    */
    'parentName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "typeName",
            "baseName": "typeName",
            "type": "string"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "string"
        },
        {
            "name": "parentName",
            "baseName": "parentName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AssociatedItemBean.attributeTypeMap;
    }
}

