/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssociatedItemBean } from './associatedItemBean';
import { ChangedValueBean } from './changedValueBean';

/**
* An audit record.
*/
export class AuditRecordBean {
    /**
    * The ID of the audit record.
    */
    'id'?: number;
    /**
    * The summary of the audit record.
    */
    'summary'?: string;
    /**
    * The URL of the computer where the creation of the audit record was initiated.
    */
    'remoteAddress'?: string;
    /**
    * The key of the user who created the audit record.
    */
    'authorKey'?: string;
    /**
    * The date and time on which the audit record was created.
    */
    'created'?: Date;
    /**
    * The category of the audit record. For a list of these categories, see the help article [Auditing in Jira applications](https://confluence.atlassian.com/x/noXKM).
    */
    'category'?: string;
    /**
    * The event the audit record originated from.
    */
    'eventSource'?: string;
    /**
    * The description of the audit record.
    */
    'description'?: string;
    'objectItem'?: AssociatedItemBean;
    /**
    * The list of values changed in the record event.
    */
    'changedValues'?: Array<ChangedValueBean>;
    /**
    * The list of items associated with the changed record.
    */
    'associatedItems'?: Array<AssociatedItemBean>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "remoteAddress",
            "baseName": "remoteAddress",
            "type": "string"
        },
        {
            "name": "authorKey",
            "baseName": "authorKey",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "eventSource",
            "baseName": "eventSource",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "objectItem",
            "baseName": "objectItem",
            "type": "AssociatedItemBean"
        },
        {
            "name": "changedValues",
            "baseName": "changedValues",
            "type": "Array<ChangedValueBean>"
        },
        {
            "name": "associatedItems",
            "baseName": "associatedItems",
            "type": "Array<AssociatedItemBean>"
        }    ];

    static getAttributeTypeMap() {
        return AuditRecordBean.attributeTypeMap;
    }
}

