/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AutoCompleteSuggestion } from './autoCompleteSuggestion';

/**
* The results from a JQL query.
*/
export class AutoCompleteSuggestions {
    /**
    * The list of suggested item.
    */
    'results'?: Array<AutoCompleteSuggestion>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<AutoCompleteSuggestion>"
        }    ];

    static getAttributeTypeMap() {
        return AutoCompleteSuggestions.attributeTypeMap;
    }
}

