/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueFilterForBulkPropertySet } from './issueFilterForBulkPropertySet';

/**
* Bulk issue property update request details.
*/
export class BulkIssuePropertyUpdateRequest {
    /**
    * The value of the property. The value must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
    */
    'value'?: object;
    /**
    * The bulk operation filter.
    */
    'filter'?: IssueFilterForBulkPropertySet;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "object"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "IssueFilterForBulkPropertySet"
        }    ];

    static getAttributeTypeMap() {
        return BulkIssuePropertyUpdateRequest.attributeTypeMap;
    }
}

