/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JQLQueryWithUnknownUsers } from './jQLQueryWithUnknownUsers';

/**
* The converted JQL queries.
*/
export class ConvertedJQLQueries {
    /**
    * The list of converted query strings with account IDs in place of user identifiers.
    */
    'queryStrings'?: Array<string>;
    /**
    * List of queries containing user information that could not be mapped to an existing user
    */
    'queriesWithUnknownUsers'?: Array<JQLQueryWithUnknownUsers>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "queryStrings",
            "baseName": "queryStrings",
            "type": "Array<string>"
        },
        {
            "name": "queriesWithUnknownUsers",
            "baseName": "queriesWithUnknownUsers",
            "type": "Array<JQLQueryWithUnknownUsers>"
        }    ];

    static getAttributeTypeMap() {
        return ConvertedJQLQueries.attributeTypeMap;
    }
}

