/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContextID } from './contextID';
import { JsonTypeBean } from './jsonTypeBean';
import { ScreenID } from './screenID';

/**
* Details of a field.
*/
export class Field {
    /**
    * The id of the field.
    */
    'id': string;
    /**
    * The name of the field.
    */
    'name': string;
    'schema'?: JsonTypeBean;
    /**
    * The description of the field.
    */
    'description'?: string;
    /**
    * The key of the field.
    */
    'key'?: string;
    /**
    * List of screens where the field is used.
    */
    'screens'?: Array<ScreenID>;
    /**
    * List of contexts where the field is used.
    */
    'contexts'?: Array<ContextID>;
    /**
    * The date when the value of the field last changed.
    */
    'lastUsed'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "JsonTypeBean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "screens",
            "baseName": "screens",
            "type": "Array<ScreenID>"
        },
        {
            "name": "contexts",
            "baseName": "contexts",
            "type": "Array<ContextID>"
        },
        {
            "name": "lastUsed",
            "baseName": "lastUsed",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Field.attributeTypeMap;
    }
}

