/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* An operand that is a function. See [Advanced searching - functions reference](https://confluence.atlassian.com/x/dwiiLQ) for more information about JQL functions.
*/
export class FunctionOperand {
    /**
    * The name of the function.
    */
    '_function': string;
    /**
    * The list of function arguments.
    */
    'arguments'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_function",
            "baseName": "function",
            "type": "string"
        },
        {
            "name": "arguments",
            "baseName": "arguments",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return FunctionOperand.attributeTypeMap;
    }
}

