/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GlobalScopeBean {
    /**
    * Defines the behavior of the option in the global context.If notSelectable is set, the option cannot be set as the field\'s value. This is useful for archiving an option that has previously been selected but shouldn\'t be used anymore.If defaultValue is set, the option is selected by default.
    */
    'attributes'?: Array<GlobalScopeBean.AttributesEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<GlobalScopeBean.AttributesEnum>"
        }    ];

    static getAttributeTypeMap() {
        return GlobalScopeBean.attributeTypeMap;
    }
}

export namespace GlobalScopeBean {
    export enum AttributesEnum {
        NotSelectable = <any> 'notSelectable',
        DefaultValue = <any> 'defaultValue'
    }
}
