/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class HierarchyLevel {
    'id'?: number;
    'name'?: string;
    'aboveLevelId'?: number;
    'belowLevelId'?: number;
    'projectConfigurationId'?: number;
    'issueTypeIds'?: Array<number>;
    'externalUuid'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "aboveLevelId",
            "baseName": "aboveLevelId",
            "type": "number"
        },
        {
            "name": "belowLevelId",
            "baseName": "belowLevelId",
            "type": "number"
        },
        {
            "name": "projectConfigurationId",
            "baseName": "projectConfigurationId",
            "type": "number"
        },
        {
            "name": "issueTypeIds",
            "baseName": "issueTypeIds",
            "type": "Array<number>"
        },
        {
            "name": "externalUuid",
            "baseName": "externalUuid",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HierarchyLevel.attributeTypeMap;
    }
}

