/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueMatchesForJQL } from './issueMatchesForJQL';

/**
* A list of matched issues or errors for each JQL query, in the order the JQL queries were passed.
*/
export class IssueMatches {
    'matches': Array<IssueMatchesForJQL>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "matches",
            "baseName": "matches",
            "type": "Array<IssueMatchesForJQL>"
        }    ];

    static getAttributeTypeMap() {
        return IssueMatches.attributeTypeMap;
    }
}

