/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SuggestedIssue } from './suggestedIssue';

/**
* A type of issue suggested for use in auto-completion.
*/
export class IssuePickerSuggestionsIssueType {
    /**
    * The label of the type of issues suggested for use in auto-completion.
    */
    'label'?: string;
    /**
    * If issue suggestions are found, returns a message indicating the number of issues suggestions found and returned.
    */
    'sub'?: string;
    /**
    * The ID of the type of issues suggested for use in auto-completion.
    */
    'id'?: string;
    /**
    * If no issue suggestions are found, returns a message indicating no suggestions were found,
    */
    'msg'?: string;
    /**
    * A list of issues suggested for use in auto-completion.
    */
    'issues'?: Array<SuggestedIssue>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "sub",
            "baseName": "sub",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string"
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<SuggestedIssue>"
        }    ];

    static getAttributeTypeMap() {
        return IssuePickerSuggestionsIssueType.attributeTypeMap;
    }
}

