/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Details about the mapping between an issue type and a workflow.
*/
export class IssueTypeWorkflowMapping {
    /**
    * The ID of the issue type. Not required if updating the issue type-workflow mapping.
    */
    'issueType'?: string;
    /**
    * The name of the workflow.
    */
    'workflow'?: string;
    /**
    * Set to true to create or update the draft of a workflow scheme and update the mapping in the draft, when the workflow scheme cannot be edited. Defaults to `false`. Only applicable when updating the workflow-issue types mapping.
    */
    'updateDraftIfNeeded'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "issueType",
            "baseName": "issueType",
            "type": "string"
        },
        {
            "name": "workflow",
            "baseName": "workflow",
            "type": "string"
        },
        {
            "name": "updateDraftIfNeeded",
            "baseName": "updateDraftIfNeeded",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return IssueTypeWorkflowMapping.attributeTypeMap;
    }
}

