/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FieldMetadata } from './fieldMetadata';
import { StatusDetails } from './statusDetails';

/**
* Details of an issue transition.
*/
export class IssueTransition extends null<String, object> {
    /**
    * The ID of the issue transition. Required when specifying a transition to undertake.
    */
    'id'?: string;
    /**
    * The name of the issue transition.
    */
    'name'?: string;
    /**
    * Details of the issue status after the transition.
    */
    'to'?: StatusDetails;
    /**
    * Indicates whether there is a screen associated with the issue transition.
    */
    'hasScreen'?: boolean;
    /**
    * Indicates whether the issue transition is global, that is, the transition is applied to issues regardless of their status.
    */
    'isGlobal'?: boolean;
    /**
    * Indicates whether this is the initial issue transition for the workflow.
    */
    'isInitial'?: boolean;
    /**
    * Indicates whether the issue has to meet certain criteria before the issue transition is applied.
    */
    'isConditional'?: boolean;
    /**
    * Details of the fields associated with the issue transition screen. Use this information to populate `fields` and `update` in a transition request.
    */
    'fields'?: { [key: string]: FieldMetadata; };
    /**
    * Expand options that include additional transition details in the response.
    */
    'expand'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "StatusDetails"
        },
        {
            "name": "hasScreen",
            "baseName": "hasScreen",
            "type": "boolean"
        },
        {
            "name": "isGlobal",
            "baseName": "isGlobal",
            "type": "boolean"
        },
        {
            "name": "isInitial",
            "baseName": "isInitial",
            "type": "boolean"
        },
        {
            "name": "isConditional",
            "baseName": "isConditional",
            "type": "boolean"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: FieldMetadata; }"
        },
        {
            "name": "expand",
            "baseName": "expand",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(IssueTransition.attributeTypeMap);
    }
}

