/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FieldMetadata } from './fieldMetadata';
import { Scope } from './scope';

/**
* Details of the issue creation metadata for an issue type.
*/
export class IssueTypeIssueCreateMetadata {
    /**
    * The URL of these issue type details.
    */
    'self'?: string;
    /**
    * The ID of the issue type.
    */
    'id'?: string;
    /**
    * The description of the issue type.
    */
    'description'?: string;
    /**
    * The URL of the issue type\'s avatar.
    */
    'iconUrl'?: string;
    /**
    * The name of the issue type.
    */
    'name'?: string;
    /**
    * Indicates whether this issue type is used to create subtasks.
    */
    'subtask'?: boolean;
    /**
    * The ID of the issue type\'s avatar.
    */
    'avatarId'?: number;
    /**
    * project unique ID for next-gen entities
    */
    'entityId'?: string;
    /**
    * Details of the next-gen projects the issue type is available in.
    */
    'scope'?: Scope;
    /**
    * Expand options that include additional issue type metadata details in the response.
    */
    'expand'?: string;
    /**
    * List of the fields available when creating an issue for the issue type.
    */
    'fields'?: { [key: string]: FieldMetadata; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "iconUrl",
            "baseName": "iconUrl",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "subtask",
            "baseName": "subtask",
            "type": "boolean"
        },
        {
            "name": "avatarId",
            "baseName": "avatarId",
            "type": "number"
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "Scope"
        },
        {
            "name": "expand",
            "baseName": "expand",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: FieldMetadata; }"
        }    ];

    static getAttributeTypeMap() {
        return IssueTypeIssueCreateMetadata.attributeTypeMap;
    }
}

