/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Comment } from './comment';
import { IssueLinkType } from './issueLinkType';
import { LinkedIssue } from './linkedIssue';

export class LinkIssueRequestJsonBean {
    'type'?: IssueLinkType;
    'inwardIssue'?: LinkedIssue;
    'outwardIssue'?: LinkedIssue;
    'comment'?: Comment;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "IssueLinkType"
        },
        {
            "name": "inwardIssue",
            "baseName": "inwardIssue",
            "type": "LinkedIssue"
        },
        {
            "name": "outwardIssue",
            "baseName": "outwardIssue",
            "type": "LinkedIssue"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "Comment"
        }    ];

    static getAttributeTypeMap() {
        return LinkIssueRequestJsonBean.attributeTypeMap;
    }
}

