/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JqlQueryUnitaryOperand } from './jqlQueryUnitaryOperand';

/**
* An operand that is a list of values.
*/
export class ListOperand {
    /**
    * The list of operand values.
    */
    'values'?: Array<JqlQueryUnitaryOperand>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<JqlQueryUnitaryOperand>"
        }    ];

    static getAttributeTypeMap() {
        return ListOperand.attributeTypeMap;
    }
}

