/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecurityLevel } from './securityLevel';

/**
* List of issue level security items in a project.
*/
export class ProjectIssueSecurityLevels {
    /**
    * Issue level security items list.
    */
    'levels': Array<SecurityLevel>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "levels",
            "baseName": "levels",
            "type": "Array<SecurityLevel>"
        }    ];

    static getAttributeTypeMap() {
        return ProjectIssueSecurityLevels.attributeTypeMap;
    }
}

