/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectForScope } from './projectForScope';

/**
* The scope of an entity. Indicated for entities associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO).
*/
export class Scope extends null<String, object> {
    /**
    * The type of scope.
    */
    'type'?: Scope.TypeEnum;
    /**
    * The project the entity has scope in.
    */
    'project'?: ProjectForScope;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "Scope.TypeEnum"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "ProjectForScope"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Scope.attributeTypeMap);
    }
}

export namespace Scope {
    export enum TypeEnum {
        PROJECT = <any> 'PROJECT',
        TEMPLATE = <any> 'TEMPLATE'
    }
}
