/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueBean } from './issueBean';
import { JsonTypeBean } from './jsonTypeBean';

/**
* The result of a JQL search.
*/
export class SearchResults {
    /**
    * Expand options that include additional search result details in the response.
    */
    'expand'?: string;
    /**
    * The index of the first item returned on the page.
    */
    'startAt'?: number;
    /**
    * The maximum number of results that could be on the page.
    */
    'maxResults'?: number;
    /**
    * The number of results on the page.
    */
    'total'?: number;
    /**
    * The list of issues found by the search.
    */
    'issues'?: Array<IssueBean>;
    /**
    * Any warnings related to the JQL query.
    */
    'warningMessages'?: Array<string>;
    /**
    * The ID and name of each field in the search results.
    */
    'names'?: { [key: string]: string; };
    /**
    * The schema describing the field types in the search results.
    */
    'schema'?: { [key: string]: JsonTypeBean; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expand",
            "baseName": "expand",
            "type": "string"
        },
        {
            "name": "startAt",
            "baseName": "startAt",
            "type": "number"
        },
        {
            "name": "maxResults",
            "baseName": "maxResults",
            "type": "number"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<IssueBean>"
        },
        {
            "name": "warningMessages",
            "baseName": "warningMessages",
            "type": "Array<string>"
        },
        {
            "name": "names",
            "baseName": "names",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "{ [key: string]: JsonTypeBean; }"
        }    ];

    static getAttributeTypeMap() {
        return SearchResults.attributeTypeMap;
    }
}

