/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkflowTransitionRulesUpdateErrorDetails } from './workflowTransitionRulesUpdateErrorDetails';

/**
* Details of any errors encountered while updating workflow transition rules.
*/
export class WorkflowTransitionRulesUpdateErrors {
    /**
    * A list of workflows.
    */
    'updateResults': Array<WorkflowTransitionRulesUpdateErrorDetails>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "updateResults",
            "baseName": "updateResults",
            "type": "Array<WorkflowTransitionRulesUpdateErrorDetails>"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowTransitionRulesUpdateErrors.attributeTypeMap;
    }
}

