/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConnectWorkflowTransitionRule } from './connectWorkflowTransitionRule';
import { WorkflowId } from './workflowId';

/**
* A workflow with transition rules.
*/
export class WorkflowTransitionRules {
    'workflowId'?: WorkflowId;
    /**
    * The list of post functions within the workflow.
    */
    'postFunctions'?: Array<ConnectWorkflowTransitionRule>;
    /**
    * The list of conditions within the workflow.
    */
    'conditions'?: Array<ConnectWorkflowTransitionRule>;
    /**
    * The list of validators within the workflow.
    */
    'validators'?: Array<ConnectWorkflowTransitionRule>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workflowId",
            "baseName": "workflowId",
            "type": "WorkflowId"
        },
        {
            "name": "postFunctions",
            "baseName": "postFunctions",
            "type": "Array<ConnectWorkflowTransitionRule>"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<ConnectWorkflowTransitionRule>"
        },
        {
            "name": "validators",
            "baseName": "validators",
            "type": "Array<ConnectWorkflowTransitionRule>"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowTransitionRules.attributeTypeMap;
    }
}

