/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkflowTransitionRule } from './workflowTransitionRule';

/**
* A collection of transition rules.
*/
export class WorkflowRules {
    /**
    * The workflow conditions.
    */
    'conditions': Array<WorkflowTransitionRule>;
    /**
    * The workflow validators.
    */
    'validators': Array<WorkflowTransitionRule>;
    /**
    * The workflow post functions.
    */
    'postFunctions': Array<WorkflowTransitionRule>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<WorkflowTransitionRule>"
        },
        {
            "name": "validators",
            "baseName": "validators",
            "type": "Array<WorkflowTransitionRule>"
        },
        {
            "name": "postFunctions",
            "baseName": "postFunctions",
            "type": "Array<WorkflowTransitionRule>"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowRules.attributeTypeMap;
    }
}

