/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Author } from './author';
import { BaseCommitAllOf } from './baseCommitAllOf';
import { IssueAllOfContent } from './issueAllOfContent';
import { ModelObject } from './modelObject';

export class BaseCommit extends ModelObject {
    'hash'?: string;
    'date'?: Date;
    'author'?: Author;
    'message'?: string;
    'summary'?: IssueAllOfContent;
    'parents'?: Array<BaseCommit>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "Author"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "IssueAllOfContent"
        },
        {
            "name": "parents",
            "baseName": "parents",
            "type": "Array<BaseCommit>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(BaseCommit.attributeTypeMap);
    }
}

