/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './account';
import { ModelObject } from './modelObject';
import { PipelineAllOf } from './pipelineAllOf';
import { PipelineState } from './pipelineState';
import { PipelineTarget } from './pipelineTarget';
import { PipelineTrigger } from './pipelineTrigger';
import { Repository } from './repository';

export class Pipeline extends ModelObject {
    /**
    * The UUID identifying the pipeline.
    */
    'uuid'?: string;
    /**
    * The build number of the pipeline.
    */
    'buildNumber'?: number;
    'creator'?: Account;
    'repository'?: Repository;
    'target'?: PipelineTarget;
    'trigger'?: PipelineTrigger;
    'state'?: PipelineState;
    /**
    * The timestamp when the pipeline was created.
    */
    'createdOn'?: Date;
    /**
    * The timestamp when the Pipeline was completed. This is not set if the pipeline is still in progress.
    */
    'completedOn'?: Date;
    /**
    * The number of build seconds used by this pipeline.
    */
    'buildSecondsUsed'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "buildNumber",
            "baseName": "build_number",
            "type": "number"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "Account"
        },
        {
            "name": "repository",
            "baseName": "repository",
            "type": "Repository"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "PipelineTarget"
        },
        {
            "name": "trigger",
            "baseName": "trigger",
            "type": "PipelineTrigger"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "PipelineState"
        },
        {
            "name": "createdOn",
            "baseName": "created_on",
            "type": "Date"
        },
        {
            "name": "completedOn",
            "baseName": "completed_on",
            "type": "Date"
        },
        {
            "name": "buildSecondsUsed",
            "baseName": "build_seconds_used",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Pipeline.attributeTypeMap);
    }
}

