/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A Bitbucket Pipelines IN_PROGRESS pipeline step state.
*/
export class PipelineStepStateInProgressAllOf {
    /**
    * The name of pipeline step state (IN_PROGRESS).
    */
    'name'?: PipelineStepStateInProgressAllOf.NameEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "PipelineStepStateInProgressAllOf.NameEnum"
        }    ];

    static getAttributeTypeMap() {
        return PipelineStepStateInProgressAllOf.attributeTypeMap;
    }
}

export namespace PipelineStepStateInProgressAllOf {
    export enum NameEnum {
        INPROGRESS = <any> 'IN_PROGRESS'
    }
}
