/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A representation of the selector that was used to identify the pipeline in the YML file.
*/
export class PipelineSelectorAllOf {
    /**
    * The type of selector.
    */
    'type'?: PipelineSelectorAllOf.TypeEnum;
    /**
    * The name of the matching pipeline definition.
    */
    'pattern'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PipelineSelectorAllOf.TypeEnum"
        },
        {
            "name": "pattern",
            "baseName": "pattern",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PipelineSelectorAllOf.attributeTypeMap;
    }
}

export namespace PipelineSelectorAllOf {
    export enum TypeEnum {
        Branches = <any> 'branches',
        Tags = <any> 'tags',
        Bookmarks = <any> 'bookmarks',
        Default = <any> 'default',
        Custom = <any> 'custom'
    }
}
