/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PipelineStateCompletedExpiredAllOf } from './pipelineStateCompletedExpiredAllOf';
import { PipelineStateCompletedResult } from './pipelineStateCompletedResult';

export class PipelineStateCompletedExpired {
    'type': string;
    /**
    * The name of the stopped result (EXPIRED).
    */
    'name'?: PipelineStateCompletedExpired.NameEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "PipelineStateCompletedExpired.NameEnum"
        }    ];

    static getAttributeTypeMap() {
        return PipelineStateCompletedExpired.attributeTypeMap;
    }
}

export namespace PipelineStateCompletedExpired {
    export enum NameEnum {
        EXPIRED = <any> 'EXPIRED'
    }
}
