/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PipelineStateInProgressPausedAllOf } from './pipelineStateInProgressPausedAllOf';
import { PipelineStateInProgressStage } from './pipelineStateInProgressStage';

export class PipelineStateInProgressPaused {
    'type': string;
    /**
    * The name of the stage (PAUSED)
    */
    'name'?: PipelineStateInProgressPaused.NameEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "PipelineStateInProgressPaused.NameEnum"
        }    ];

    static getAttributeTypeMap() {
        return PipelineStateInProgressPaused.attributeTypeMap;
    }
}

export namespace PipelineStateInProgressPaused {
    export enum NameEnum {
        PAUSED = <any> 'PAUSED'
    }
}
