/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Pipeline } from './pipeline';
import { PipelineScheduleExecution } from './pipelineScheduleExecution';
import { PipelineScheduleExecutionExecutedAllOf } from './pipelineScheduleExecutionExecutedAllOf';

export class PipelineScheduleExecutionExecuted {
    'type': string;
    'pipeline'?: Pipeline;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "pipeline",
            "baseName": "pipeline",
            "type": "Pipeline"
        }    ];

    static getAttributeTypeMap() {
        return PipelineScheduleExecutionExecuted.attributeTypeMap;
    }
}

