/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PipelineStepState } from './pipelineStepState';
import { PipelineStepStateReadyAllOf } from './pipelineStepStateReadyAllOf';

export class PipelineStepStateReady {
    'type': string;
    /**
    * The name of pipeline step state (READY).
    */
    'name'?: PipelineStepStateReady.NameEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "PipelineStepStateReady.NameEnum"
        }    ];

    static getAttributeTypeMap() {
        return PipelineStepStateReady.attributeTypeMap;
    }
}

export namespace PipelineStepStateReady {
    export enum NameEnum {
        READY = <any> 'READY'
    }
}
