/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchCodeSearchResult } from './searchCodeSearchResult';

export class SearchResultPage {
    'size'?: number;
    'page'?: number;
    'pagelen'?: number;
    'querySubstituted'?: boolean;
    'next'?: string;
    'previous'?: string;
    'values'?: Array<SearchCodeSearchResult>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "pagelen",
            "baseName": "pagelen",
            "type": "number"
        },
        {
            "name": "querySubstituted",
            "baseName": "query_substituted",
            "type": "boolean"
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<SearchCodeSearchResult>"
        }    ];

    static getAttributeTypeMap() {
        return SearchResultPage.attributeTypeMap;
    }
}

