/**
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A user object.
*/
export class UserAllOf {
    'isStaff'?: boolean;
    /**
    * The user\'s Atlassian account ID.
    */
    'accountId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isStaff",
            "baseName": "is_staff",
            "type": "boolean"
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserAllOf.attributeTypeMap;
    }
}

